### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by teamtopkarl** [zilong3033/fastjsonScan#1]
java.lang.ClassNotFoundException: sun.misc.BASE64Encoder
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at burp.BurpExtender.buildPayload(BurpExtender.java:224)
	at burp.BurpExtender.ScanFastjson24echo(BurpExtender.java:242)
	at burp.BurpExtender.doScan(BurpExtender.java:140)
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:91)
	at burp.d3.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by zilong3033** [comment]
高版本的没这个base64，抽空更新下。

**Comment by teamtopkarl** [comment]
嗯，BP3.3能出结果，但后面也出错了------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月23日(星期五) 晚上11:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zilong3033/fastjsonScan] 报错 (#1)
